### ISSUE TITLE
custom armor like black

### ISSUE THREAD

**Issue by tajtinorbi** [PluginBugs/Issues-ItemsAdder#3583]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

dephloy3r

### What happened?

Hello!
some custom armor textures are broken on my server, like i see the dark armor.
![kép_2024-04-28_113802602](https://github.com/PluginBugs/Issues-ItemsAdder/assets/63115766/3bad31e3-806a-48fd-88d2-2f32063a0bb2)

### Steps to reproduce the issue

no need made anything i try delete server textures and after back but nothing

### Server version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version

### ItemsAdder Version

3.6.3-beta-6

### ProtocolLib Version

5.2.0-SNAPSHOT-679

### LoneLibs Version

1.0.45

### Full server log

https://mclo.gs/rscK7HS

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/63115766/900f8dfb-cfe8-48cb-b042-b7e7abf29efd)

**Comment by Andre601** [comment]
You are using an outdated version of ItemsAdder. Please update it and all its dependencies before reporting an issue, as it may already be fixed by that point.

**Comment by tajtinorbi** [comment]
i now update the items adder to version: 3.6.3-beta-14

**Comment by tajtinorbi** [comment]
i already update but nothing

**Comment by tajtinorbi** [comment]
Alright, so we updated the plugins cleared caches and regenerated the texture. Still not working.
We have checked our files to find the issue but we couldn't find it.

Which files should ItemsAdder generate?
We have texture files under `minecraft/textures/models/armor` and item models under `minecraft/models` like `leather_boots.json`.

The armor works perfectly as an item.
But we cannot find the model of the weared armor. Should be there any?

**Comment by tajtinorbi** [comment]
Alright, so we updated the plugins cleared caches and regenerated the texture. Still not working.
We have checked our files to find the issue but we couldn't find it.

Which files should ItemsAdder generate?
We have texture files under `minecraft/textures/models/armor` and item models under `minecraft/models` like `leather_boots.json`.

The armor works perfectly as an item.
But we cannot find the model of the weared armor. Should be there any?
